global:
  smtp_smarthost: 'smtp.sendgrid.net:587'
  smtp_from: 'freekstratenn@gmail.com'
  smtp_auth_username: 'apikey'
  smtp_auth_password: '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'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'freekstratenn@gmail.com'
        send_resolved: true