services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mijn-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: myapp
    volumes:
      - ./data/mongodb:/data/db
    restart: unless-stopped

  # Je API service
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: mijn-api
    ports:
      - "3000:12345"
    environment:
      MONGO_URL: mongodb://admin:password123@mongodb:27017/myapp?authSource=admin
      PORT: 12345
    depends_on:
      - mongodb
    restart: unless-stopped