services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mijn-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: myapp
    volumes:
      - ./data/mongodb:/data/db
    restart: unless-stopped
    # Healthcheck toevoegen voor MongoDB
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/myapp --quiet
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Je API service
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: mijn-api
    ports:
      - "3000:12345"
    environment:
      MONGO_URL: mongodb://admin:password123@mongodb:27017/myapp?authSource=admin
      PORT: 12345
    depends_on:
      mongodb:
        condition: service_healthy  # Wacht tot MongoDB healthy is
    restart: unless-stopped

  # Nieuwe frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mijn-frontend
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped