services:
  # Remove the entire mongodb service block

  # Je API service - updated to use local MongoDB
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: mijn-api
    ports:
      - "3000:12345"
    environment:
      MONGO_URL: mongodb://host.docker.internal:27017/myapp
      PORT: 12345
      DB_NAME: myapp
    # Remove depends_on for mongodb since we're using local
    restart: unless-stopped

  # Frontend service (unchanged)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mijn-frontend
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped