services:
  mongodb:
    image: mongo:latest
    container_name: mijn-mongo
    volumes:
      - ./data:/data/db
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: mijn-api
    ports:
      - "80:12345"  # Changed to port 80 for Bunnyshell
    environment:
      MONGO_URL: mongodb://mijn-mongo:27017
      PORT: 12345
      DB_NAME: myapp
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Now with capital D
    container_name: mijn-frontend
    ports:
      - "80:80"  # Changed to port 80 for Bunnyshell
    depends_on:
      - api
    restart: unless-stopped