global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:12345']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['db-exporter:9216']