global:
  # Note: env expansion is not enabled in this image by default.
  # Use a fixed smarthost with port to avoid startup failure; other values can be templated later.
  smtp_smarthost: 'smtp.sendgrid.net:587'
  smtp_from: ${SMTP_FROM}
  smtp_auth_username: ${SMTP_AUTH_USERNAME}
  smtp_auth_password: ${SMTP_AUTH_PASSWORD}
  smtp_require_tls: ${SMTP_REQUIRE_TLS}

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 3h
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: '${ALERT_EMAIL_TO}'
        headers:
          Subject: 'DevOps Alert: {{ .GroupLabels.alertname }}'
        html: |
          <h2>Alert Details</h2>
          {{ range .Alerts }}
          <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Status:</strong> {{ .Status }}</p>
          <p><strong>Started:</strong> {{ .StartsAt }}</p>
          <hr>
          {{ end }}
        text: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Status: {{ .Status }}
          Started: {{ .StartsAt }}
          ---
          {{ end }}
        send_resolved: true
