global:
  smtp_smarthost: 'smtp.sendgrid.net:587'
  smtp_from: '${ALERT_EMAIL_FROM}'
  smtp_auth_username: 'apikey'
  smtp_auth_password: '${SENDGRID_API_KEY}'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: '${ALERT_EMAIL_TO}'
        send_resolved: true