global:
  smtp_smarthost: 'smtp.sendgrid.net:587'
  smtp_from: 'freekstraten@gmail.com'
  smtp_auth_username: 'apikey'
  smtp_auth_password: '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'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 3h
  receiver: 'email-notifications'

receivers:
  - name: 'email-notifications'
    email_configs:
      - to: 'freekstraten@gmail.com'
        subject: 'DevOps Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Status: {{ .Status }}
          Started: {{ .StartsAt }}
          {{ end }}
        send_resolved: true