name: Bunnyshell - Deploy Preview Environment

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  deploy-preview:
    uses: bunnyshell/workflows/.github/workflows/prepare-and-deploy-env.yaml@v2
    with:
      project-id: ${{ vars.BUNNYSHELL_PROJECT_ID }}
      cluster-id: ${{ vars.BUNNYSHELL_CLUSTER_ID }}
      pr-number: ${{ github.event.number }}
      comment-on-pr: true
      git-ref: ${{ github.event.pull_request.head.sha }}
      # Alternative options for git-ref:
      # git-ref: ${{ github.event.pull_request.head.ref }}  # branch name
      # git-ref: ${{ github.sha }}  # current commit
    secrets:
      bunnyshell-access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}