# .bunnyshell/bunnyshell.yaml
kind: Environment
name: "preview" # Generieke naam voor de preview-configuratie
type: primary
# De urlHandle wordt vaak dynamisch gegenereerd/overschreven door de Bunnyshell actie
# op basis van het PR nummer, om uniekheid te garanderen.
# Zet hier een placeholder als je de instructie letterlijk volgt.
urlHandle: "jouw-app-preview-placeholder"
environmentVariables:
  DemoVarDefinedInBunnyshell: demo-value
components:
  - name: mongodb
    kind: Service
    dockerCompose:
      image: 'mongo:latest'
      restart: unless-stopped
      volumes:
        - './data:/data/db' # Let op: volumes in Kubernetes werken anders dan lokaal.
        # Dit is mogelijk niet direct functioneel zonder PersistentVolumeClaims.
    ports:
      - port: 27017
        name: mongo
        protocol: TCP

  - name: api
    kind: Service
    dockerCompose:
      environment:
        PORT: 12345
        MONGO_URL: 'mongodb://mongodb:27017'
        DB_NAME: myapp
      build:
        context: .
        dockerfile: Dockerfile.prod
      depends_on:
        - mongodb
      restart: unless-stopped
    ports:
      - port: 12345
        name: api
        protocol: TCP
        public: true

  - name: frontend
    kind: Service
    dockerCompose:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      depends_on:
        - api
      restart: unless-stopped
    ports:
      - port: 80
        name: frontend
        protocol: TCP
        public: true