name: Bunnyshell - Deploy Preview Environment

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write
  actions: read

jobs:
  deploy-preview:
    uses: bunnyshell/workflows/.github/workflows/deploy-env.yaml@v2.1.0
    with:
      project-id: ${{ vars.BUNNYSHELL_PROJECT_ID }}
      cluster-id: ${{ vars.BUNNYSHELL_CLUSTER_ID }}
      bunnyshell-yaml-path: .bunnyshell/bunnyshell.yml
      pr-number: ${{ github.event.number }}
      comment-on-pr: true
      allowed-users: "*"
    secrets:
      bunnyshell-access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}