name: Deploy preview environment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Deploy environment
        uses: bunnyshell/deploy-env-action@v2
        with:
          bunnyshell-access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}
          bunnyshell-environment-project-id: ${{ vars.BUNNYSHELL_PROJECT_ID }}
          bunnyshell-k8s-cluster-id: ${{ vars.BUNNYSHELL_CLUSTER_ID }}
          bunnyshell-yaml-path: .bunnyshell/bunnyshell.yaml
          allowed-users: "*"