
name: Bunnyshell - Deploy Preview Environment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    uses: bunnyshell/workflows/.github/workflows/deploy-env.yaml@main
    with:
      project-id: ${{ vars.BUNNYSHELL_PROJECT_ID }}
      cluster-id: ${{ vars.BUNNYSHELL_CLUSTER_ID }}
      bunnyshell-yaml-path: .bunnyshell/bunnyshell.yaml
      pr-number: ${{ github.event.number }}
      comment-on-pr: true
      allowed-users: "*"
    secrets:
      bunnyshell-access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}