name: Bunnyshell - Deploy Preview Environment

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  deploy-preview:
    # Use the prepare-and-deploy workflow instead of deploy-env
    uses: bunnyshell/workflows/.github/workflows/prepare-and-deploy-env.yaml@v2
    with:
      project-id: ${{ vars.BUNNYSHELL_PROJECT_ID }}
      cluster-id: ${{ vars.BUNNYSHELL_CLUSTER_ID }}
      pr-number: ${{ github.event.number }}
      comment-on-pr: true
      # This workflow should handle creating the environment
    secrets:
      bunnyshell-access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}