name: Bunnyshell - Deploy Preview Environment

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write
  actions: read

jobs:
  # Add a simple test job first
  test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Test Trigger
        run: |
          echo "Deploy workflow triggered successfully!"
          echo "PR Number: ${{ github.event.number }}"
          echo "Event Action: ${{ github.event.action }}"

  deploy-preview:
    runs-on: ubuntu-latest
    needs: test-trigger
    # Add condition to ensure required vars exist
    if: ${{ vars.BUNNYSHELL_PROJECT_ID != '' && vars.BUNNYSHELL_CLUSTER_ID != '' && secrets.BUNNYSHELL_ACCESS_TOKEN != '' }}

    steps:
      - name: Deploy with Bunnyshell
        uses: bunnyshell/cli@v2
        with:
          project-id: ${{ vars.BUNNYSHELL_PROJECT_ID }}
          cluster-id: ${{ vars.BUNNYSHELL_CLUSTER_ID }}
          pr-number: ${{ github.event.number }}
          comment-on-pr: true
          bunnyshell-yaml-path: '.bunnyshell/bunnyshell.yaml'
          access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}

  # Alternative: Use the reusable workflow but with better error handling
  deploy-preview-alternative:
    runs-on: ubuntu-latest
    needs: test-trigger
    if: ${{ failure() }} # Only run if the above fails

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Preview Environment
        uses: bunnyshell/workflows/.github/workflows/deploy-env.yaml@v2
        with:
          project-id: ${{ vars.BUNNYSHELL_PROJECT_ID }}
          cluster-id: ${{ vars.BUNNYSHELL_CLUSTER_ID }}
          pr-number: ${{ github.event.number }}
          comment-on-pr: true
          bunnyshell-yaml-path: '.bunnyshell/bunnyshell.yaml'
        secrets:
          bunnyshell-access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}