name: Bunnyshell - Delete Preview Environment #Hi

on:
  pull_request:
    types: [closed]

jobs:
  delete-preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Delete Preview Environment
        uses: bunnyshell/workflows/.github/workflows/delete-env.yaml@v2
        with:
          bunnyshell-access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}
          bunnyshell-project-id: ${{ vars.BUNNYSHELL_PROJECT_ID }}
          bunnyshell-cluster-id: ${{ vars.BUNNYSHELL_CLUSTER_ID }}
          bunnyshell-yaml-path: .bunnyshell/bunnyshell.yaml