name: Delete preview environment

on:
  pull_request:
    types: [closed]

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Delete environment
        uses: bunnyshell/delete-env-action@v2
        with:
          bunnyshell-access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}
          bunnyshell-environment-project-id: ${{ vars.BUNNYSHELL_PROJECT_ID }}
          bunnyshell-k8s-cluster-id: ${{ vars.BUNNYSHELL_CLUSTER_ID }}
          bunnyshell-yaml-path: .bunnyshell/bunnyshell.yaml