name: Bunnyshell - Delete Preview Environment

on:
  pull_request:
    types: [closed]

jobs:
  delete-preview:
    uses: bunnyshell/workflows/.github/workflows/delete-env.yaml@v2
    with:
      bunnyshell-access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}
      bunnyshell-project-id: ${{ vars.BUNNYSHELL_PROJECT_ID }}
      bunnyshell-cluster-id: ${{ vars.BUNNYSHELL_CLUSTER_ID }}
      bunnyshell-yaml-path: .bunnyshell/bunnyshell.yaml
    secrets:
      bunnyshell-access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}