# .github/workflows/CI-API.yml

name: CI API (root)

permissions:
  contents: write       # Nodig voor write toegang tot de repo content
  checks: write         # Nodig voor het schrijven van check runs/annotations
  pull-requests: write   # Extra recht om pull request updates te doen

on:
  push:
    branches: [ "main" ]
    paths:
      - "app.js"
      - "routes/**"
      - "services/**"
      - "bin/**"
      - "scripts/**"
      - "views/**"
      - "public/**"
      - "Dockerfile*"
      - "docker-compose.yml"
      - "package.json"
      - "package-lock.json"
  pull_request:
    branches: [ "main" ]
    paths:
      - "app.js"
      - "routes/**"
      - "services/**"
      - "bin/**"
      - "scripts/**"
      - "views/**"
      - "public/**"
      - "Dockerfile*"
      - "docker-compose.yml"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Gebruik het standaard GitHub token
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        node-version: [ 18.x, 20.x, 22.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (if applicable)
        run: npm run build --if-present

      - name: Run tests
        run: npm test

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.3.1
