# .github/workflows/CI-API.yml

# De naam van deze workflow
name: CI API

# Trigger: Deze workflow wordt alleen gestart bij push of pull-request events naar de "main" branch, maar alleen als er wijzigingen zijn in de "api/**" map
on:
  push:
    branches: [ "main" ]
    paths:
      - "api/**"  # Alleen triggeren als er iets verandert in de api-map
  pull_request:
    branches: [ "main" ]
    paths:
      - "api/**"  # Alleen triggeren als er iets verandert in de api-map

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
