name: CI Notification Service

permissions:
  contents: write
  checks: write
  pull-requests: write

on:
  push:
    branches: [ "main" ]
    paths:
      - "notification-service/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "notification-service/**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

    strategy:
      matrix:
        node-version: [ 18.x, 20.x, 22.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: notification-service/package-lock.json

      - name: Install dependencies in Notification Service
        run: npm ci
        working-directory: notification-service

      - name: Build (if applicable)
        run: npm run build --if-present
        working-directory: notification-service

      - name: Run tests in Notification Service
        run: npm test
        working-directory: notification-service

      - name: Run ESLint
        run: npm run lint
        working-directory: notification-service

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.3.1
        with:
          working-directory: notification-service