name: Debug Bunnyshell Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  debug-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if secrets and variables exist
        run: |
          echo "=== Checking Configuration ==="
          echo "PROJECT_ID exists: ${{ vars.BUNNYSHELL_PROJECT_ID != '' }}"
          echo "PROJECT_ID length: ${#PROJECT_ID}"
          echo "CLUSTER_ID exists: ${{ vars.BUNNYSHELL_CLUSTER_ID != '' }}"
          echo "CLUSTER_ID length: ${#CLUSTER_ID}"
          echo "ACCESS_TOKEN exists: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN != '' }}"
        env:
          PROJECT_ID: ${{ vars.BUNNYSHELL_PROJECT_ID }}
          CLUSTER_ID: ${{ vars.BUNNYSHELL_CLUSTER_ID }}

      - name: Validate bunnyshell.yaml syntax
        run: |
          echo "=== Checking bunnyshell.yaml ==="
          if [ -f ".bunnyshell/bunnyshell.yaml" ]; then
            echo "File exists"
            # Check for common YAML issues
            python3 -c "import yaml; yaml.safe_load(open('.bunnyshell/bunnyshell.yaml'))" && echo "YAML is valid" || echo "YAML has syntax errors"
          
            # Check file encoding
            file .bunnyshell/bunnyshell.yaml
          
            # Show line endings
            cat -A .bunnyshell/bunnyshell.yaml | head -20
          else
            echo "ERROR: bunnyshell.yaml not found!"
          fi

      - name: Download and test Bunnyshell CLI
        run: |
          # Download Bunnyshell CLI
          curl -L https://github.com/bunnyshell/cli/releases/latest/download/bns-linux-amd64 -o bns
          chmod +x bns
          
          # Test CLI with access token
          echo "=== Testing Bunnyshell CLI ==="
          ./bns --version || echo "CLI version check failed"
          
          # Try to list projects
          echo "=== Attempting to list projects ==="
          ./bns projects list --access-token "${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}" || echo "Failed to list projects"
          
          # Try to validate the environment config
          echo "=== Validating environment config ==="
          ./bns environments validate --file .bunnyshell/bunnyshell.yaml || echo "Environment validation failed"