name: Debug Bunnyshell Setup

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Event Information
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "PR Number: ${{ github.event.number }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"

      - name: Check Repository Variables
        run: |
          echo "BUNNYSHELL_PROJECT_ID exists: ${{ vars.BUNNYSHELL_PROJECT_ID != '' }}"
          echo "BUNNYSHELL_CLUSTER_ID exists: ${{ vars.BUNNYSHELL_CLUSTER_ID != '' }}"
          echo "BUNNYSHELL_ACCESS_TOKEN exists: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN != '' }}"

      - name: Check bunnyshell.yaml
        run: |
          if [ -f ".bunnyshell/bunnyshell.yaml" ]; then
            echo "bunnyshell.yaml found"
            cat .bunnyshell/bunnyshell.yaml
          else
            echo "bunnyshell.yaml NOT found"
          fi