name: Test PR Trigger

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test PR trigger and secrets
        run: |
          echo "✅ PR trigger works!"
          echo "PR number: ${{ github.event.number }}"
          echo "PROJECT_ID exists: ${{ vars.BUNNYSHELL_PROJECT_ID != '' }}"
          echo "CLUSTER_ID exists: ${{ vars.BUNNYSHELL_CLUSTER_ID != '' }}"
          echo "ACCESS_TOKEN exists: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN != '' }}"