name: Test YAML Formatting

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:  # Allow manual trigger

jobs:
  test-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check line endings in bunnyshell.yaml
        run: |
          echo "=== Checking for Windows line endings (CRLF) ==="
          if file .bunnyshell/bunnyshell.yaml | grep -q "CRLF"; then
            echo "❌ ERROR: File has Windows line endings (CRLF)"
            echo "This is likely causing the deployment failure!"
          
            echo -e "\n=== Showing line endings visually ==="
            cat -A .bunnyshell/bunnyshell.yaml | head -10
            echo "..."
            echo "(^M$ indicates CRLF line endings)"
          
            exit 1
          else
            echo "✅ File has Unix line endings (LF)"
          fi

      - name: Test YAML parsing with different methods
        run: |
          echo "=== Testing YAML parsing ==="
          
          # Method 1: Python yaml
          echo "1. Python YAML parser:"
          python3 -c "
          import yaml
          try:
              with open('.bunnyshell/bunnyshell.yaml', 'r') as f:
                  data = yaml.safe_load(f)
              print('✅ Python: YAML is valid')
          except Exception as e:
              print(f'❌ Python: {e}')
          "
          
          # Method 2: Check for special characters
          echo -e "\n2. Checking for special characters:"
          if grep -P "[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]" .bunnyshell/bunnyshell.yaml; then
            echo "❌ Found special characters"
          else
            echo "✅ No special characters found"
          fi
          
          # Method 3: Check file size
          echo -e "\n3. File size check:"
          ls -la .bunnyshell/bunnyshell.yaml
          wc -l .bunnyshell/bunnyshell.yaml

      - name: Convert line endings and show difference
        run: |
          echo "=== Converting line endings ==="
          
          # Copy original
          cp .bunnyshell/bunnyshell.yaml .bunnyshell/bunnyshell.yaml.original
          
          # Convert to Unix line endings
          sed -i 's/\r$//' .bunnyshell/bunnyshell.yaml
          
          # Show if there were changes
          if diff -q .bunnyshell/bunnyshell.yaml.original .bunnyshell/bunnyshell.yaml > /dev/null; then
            echo "✅ No line ending changes needed"
          else
            echo "❌ Line endings were converted!"
            echo "Showing first few lines of difference:"
            diff -u .bunnyshell/bunnyshell.yaml.original .bunnyshell/bunnyshell.yaml | head -20
          fi

      - name: Generate PowerShell fix command
        run: |
          echo "=== PowerShell Fix Command ==="
          echo "If you're on Windows, run this in PowerShell (NOT in your IDE):"
          echo ""
          echo "cd ${{ github.workspace }}"
          echo "\$test=Get-Content .\\.bunnyshell\\bunnyshell.yaml -RAW; \$test1=\$test -Replace '\r\n', '\n'; echo -n \$test1"
          echo ""
          echo "Then copy the output and use it in bunnyshell-yaml-content in your workflow"